config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'events#index'
  resources :events do
    resources :comments, only: [:create, :destroy]
    resources :subscriptions, only: [:create, :destroy]
    resources :photos, only: [:create, :destroy]
    post :show, on: :member
  end
  resources :users, only: [:show, :edit, :update]
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :event
  belongs_to :user, optional: true

  validates :body, presence: true
  validates :user_name, presence: true, unless: -> { user.present? }

  def user_name
    if user.present?
      user.name
    else
      super
    end
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_event, only: [:create, :destroy]
  before_action :set_comment, only: [:destroy]

  # POST /comments
  def create
    @new_comment = @event.comments.build(comment_params)
    @new_comment.user = current_user

    respond_to do |f|
      if @new_comment.save
        f.html {redirect_to @event, notice: I18n.t('controllers.comments.created')}
        f.js

      else
        f.html { render action: 'new', alert: I18n.t('controllers.comments.error')}
        f.js

      end
    end

    # if @new_comment.save
    #   redirect_to @event, notice: I18n.t('controllers.comments.created')
    # else
    #   render 'events/show', alert: I18n.t('controllers.comments.error')
    # end
  end

  # DELETE /comments/1
  def destroy
    message = { notice: I18n.t('controllers.comments.destroyed') }
    
    if current_user_can_edit?(@comment)
      @comment.destroy
    else
      message = { alert: I18n.t('controllers.comments.error') }
    end

    redirect_to @event, message
  end

  private
    def set_event
      @event = Event.find(params[:event_id])
    end

    def set_comment
      @comment = @event.comments.find(params[:id])
    end

    def comment_params
      params.require(:comment).permit(:body, :user_name)
    end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_comment.html.erb
<div class="buffer-bottom">
  <p><%= comment.body %></p>
  <p>
    <span>
      <% if comment.user.present? %>
        <%= render partial: 'users/user', object: comment.user %>
      <% else %>
        <em><strong> <%= comment.user_name %> </strong></em>
      <% end %>
    </span>
  </p>
  <em><%= l comment.created_at, format: :short %></em>
  <% if current_user ==  comment.event.user %>
  <%= link_to fa_icon('trash'), event_comment_path(comment.event, comment), 
                                                    method: :delete,
                                                    data: {confirm: t('.destroy_confirm')}%>
  <% end %>
</div>

app/views/comments/_form.html.erb
<%= form_with model: comment, url: [@event, comment] do |f| %>
    <%= render partial: 'partials/form_errors', locals: {model: comment} %>

    <div class="form-group">
      <%= f.label :body %>
      <%= f.text_area :body, class: 'form-control' %>
    </div>

    <% unless user_signed_in? %>
        <div class="form-group">
          <%= f.label :user_name %>
          <%= f.text_field :user_name, class: 'form-control' %>
        </div>
    <% end %>

    <div class="actions">
      <%= f.submit 'Отправить', class: 'btn btn-primary' %>
    </div>
<% end %>

app/views/comments/create.js.erb
<%# NOTE COMMENT STEP 4: This selects `<div id="comments">` in `app/views/posts/show.html.erb` and dynamically injects the `app/views/comments/_comment.html.erb` partial. %>
window.querySelector('#comments').insertAdjacentHTML('afterbegin', '<%= escape_javascript(render @comment) %>');
<%# NOTE COMMENT STEP 4: This selects the `<form>` in `app/views/posts/show.html.erb` and resets the text area. %>
document.querySelector('.comments-form').reset();