config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'events#index'
  resources :events do
    resources :comments, only: [:create, :destroy]
    resources :subscriptions, only: [:create, :destroy]
    resources :photos, only: [:create, :destroy]
    post :show, on: :member
  end
  resources :users, only: [:show, :edit, :update]
end

app/models/photo.rb
class Photo < ApplicationRecord
  belongs_to :event
  belongs_to :user

  validates :event, presence: true
  validates :user, presence: true

  mount_uploader :photo, PhotoUploader

  scope :persisted, -> { where "id IS NOT NULL" }
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  
  before_action :set_event, only: [:create, :destroy]
  before_action :set_photo, only: [ :destroy]

  def create
    @new_photo = @event.photos.build(photo_params)
    @new_photo.user = current_user

    if @new_photo.save
      redirect_to @event, notice: I18n.t('controllers.photos.created')
    else
      render 'events/show', alert: I18n.t('controllers.photos.error')
    end
  end

  def destroy
    message = {notice:I18n.t('controllers.photos.destroyed')}

    if current_user_can_edit?(@photo)
      @photo.destroy
    else
      message = {alert: I18n.t('controllers.photos.error')}
    end
  end

  private
  
  def set_event
    @event = Event.find(params[:event_id])
  end

  def set_photo
    @photo = @event.photos.find(params[:id])
  end

  def photo_params
    params.fetch(:photo, {}).permit(:photo)
  end
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/views/photos/_form.html.erb
<%= form_for [@event, photo], html: { multipart: true } do |f| %>
  <%= render partial: 'partials/form_errors', locals: {model: photo} %>

  <div class="form-group">
    <%= f.label :photo %>
    <%= f.file_field :photo %>
  </div>

  <div class="actions">
    <%= f.submit 'Загрузить', class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/photos/_photo.html.erb
<div class="event-photo buffer-both text-left">
  
  <%= link_to image_tag(photo.photo.thumb.url), photo.photo.url %>
  <% if current_user ==  photo.event.user %>
  <%= link_to fa_icon('trash'), event_photo_path(photo.event, photo), 
                                                    method: :delete,
                                                    data: {confirm: t('.destroy_confirm')}%>
  <% end %>
  <p class="buffer-top"><%= render partial: 'users/user', object: photo.user %></p>

</div>